# Generated by Django 5.1.15 on 2026-07-26 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("crispr_designer", "CRISPR sgRNA Designer"),
                            ("primer_generator", "Primer Generator"),
                            ("codon_optimization", "Codon Optimization"),
                            ("plasmid_visualizer", "Plasmid Visualizer"),
                            ("alignment_tools", "Alignment Tools"),
                            ("hybridization", "Hybridization"),
                            ("extended_synthesis", "Extended Synthesis"),
                        ],
                        default="general",
                        max_length=64,
                    ),
                ),
                ("sequence", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gsynth_project",
                "ordering": ("-updated_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "-updated_at"],
                        name="gsynth_proj_user_id_31dfdd_idx",
                    ),
                    models.Index(
                        fields=["user", "module"], name="gsynth_proj_user_id_77aaf0_idx"
                    ),
                ],
            },
        ),
    ]
