"""Generate the wide restriction table from REBASE, via Biopython.

    python tools/generate_enzymes.py > gsynth_engine/enzyme_table.py

Why this exists. The curated set in `constants.py` is what a user *chooses*
to clone with — nineteen enzymes, the ones this lab actually keeps in the
freezer. But "does anything else cut here?" is a different question, and
answering it from nineteen enzymes gives the wrong answer: pET-21a has 60
single-cutters and the map was showing 14 of them. A diagnostic digest
planned against that map can fail on a site nobody was shown.

So the wide table is for *detection* — the plasmid map, and the check that a
design has no internal site. It is never the list you pick a cloning pair
from.

What is excluded, and why:

- **Ambiguous recognition sequences.** The site scanner matches literally;
  an enzyme whose site contains N or R would need a different matcher and
  would report positions it does not really cut.
- **Type IIS enzymes** (BsaI, BsmBI, Esp3I…), which cut *outside* their
  recognition sequence. The data model stores a cut as an offset into the
  site, so `site[cut_top:]` is empty for them — the remainders come out
  wrong rather than absent, which is worse. Supporting them means extending
  the model, not extending this table.
- **Enzymes that cut twice**, for the same reason.
- **Non-commercial enzymes.** If it cannot be ordered it cannot be used, and
  REBASE lists a great many that cannot.

Isoschizomers are collapsed. NheI, AsuNHI, BmtI, BspOI and PaeI are one
specification; listing five names for one site turns a plasmid map into
noise. The surviving name is the one this lab already uses if there is one,
otherwise the one with the most suppliers — which is a good proxy for the
name a biologist will recognise. The rest are kept as aliases so a search
still finds them.
"""
from __future__ import annotations

import sys
from collections import defaultdict

try:
    from Bio import Restriction
except ImportError:                                        # pragma: no cover
    sys.exit("Biopython is needed to regenerate this table: pip install biopython")

sys.path.insert(0, ".")
from gsynth_engine.constants import RESTRICTION_ENZYMES as CURATED  # noqa: E402


def usable(enzyme) -> bool:
    """Type IIP, unambiguous, cutting inside its own recognition sequence."""
    site = str(enzyme.site)
    if not site or set(site) - set("ACGT"):
        return False
    if enzyme.fst5 is None or enzyme.fst3 is None:
        return False
    if enzyme.cut_twice():
        return False
    top, bottom = enzyme.fst5, len(site) + enzyme.fst3
    return 0 <= top <= len(site) and 0 <= bottom <= len(site)


def canonical(names: list[str]) -> str:
    """The name a biologist will recognise, chosen deterministically."""
    for name in names:
        if name in CURATED:                     # what this lab already says
            return name
    return min(names, key=lambda n: (-len(getattr(Restriction, n).supplier_list()),
                                     len(n), n))


groups: dict[tuple[str, int, int], list[str]] = defaultdict(list)
for enzyme in Restriction.CommOnly:
    if usable(enzyme):
        site = str(enzyme.site)
        groups[(site, enzyme.fst5, len(site) + enzyme.fst3)].append(str(enzyme))

rows = []
for (site, top, bottom), names in groups.items():
    name = canonical(sorted(names))
    aliases = tuple(sorted(n for n in names if n != name))
    rows.append((name, site, top, bottom, aliases))
rows.sort()

print('"""The wide restriction table — for detection, never for selection.')
print()
print("Generated by `tools/generate_enzymes.py` from REBASE, via Biopython.")
print("Do not edit by hand: regenerate. Every entry is a distinct cut")
print("specification; isoschizomers are collapsed onto one canonical name and")
print("kept as aliases.")
print()
print("Use this to answer \"what else cuts here\". The list a user picks a")
print("cloning pair from is `RESTRICTION_ENZYMES` in `constants.py`.")
print('"""')
print("from __future__ import annotations")
print()
print("from typing import Final")
print()
print(f"#: {len(rows)} distinct specifications, from "
      f"{sum(len(v) for v in groups.values())} commercially available enzymes.")
print("ENZYME_TABLE: Final[dict[str, dict[str, object]]] = {")
for name, site, top, bottom, aliases in rows:
    alias = f', "aliases": {aliases!r}' if aliases else ""
    print(f'    "{name}": {{"recognition": "{site}", '
          f'"cut_top": {top}, "cut_bottom": {bottom}{alias}}},')
print("}")
